language: php
php:
  - '7.1'

before_script:
 - composer update --no-interaction
 - cp -rf vendor/vicimus/standard/VicimusStandard vendor/squizlabs/php_codesniffer/src/Standards


script:
  - vendor/bin/phpcs "src" "tests" --standard=VicimusStandard --report=full
  - vendor/bin/phpunit --no-coverage
