language: php
php:
  - '7.1'

before_script:
  - composer global require "squizlabs/php_codesniffer=*"
  - composer update --no-interaction

script:
  - phpcs --config-set installed_path ./vendor/vicimus/standard/VicimusStandard,./vendor/escapestudios/symfony2-coding-standard/slevomat/coding-standard
  - phpcs -i
  - vendor/bin/phpunit --no-coverage
