language: php
php:
  - '7.1'
  - '7.2'

before_script:
  - composer update --no-interaction

script:
  - vendor/bin/phpcs --standard=vendor/vicimus/standard/VicimusStandard,PSR2 --warning-severity=999 --config-set installed_paths ./vendor/slevomat/coding-standard,./vendor/escapestudios/symfony2-coding-standard "src" "tests"
  - vendor/bin/phpunit --no-coverage
