language: php
php:
  - '7.1'
  - '7.2'

before_script:
  - composer update --no-interaction
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs --config-set installed_path ./vendor/vicimus/standard/VicimusStandard,./vendor/escapestudios/symfony2-coding-standard/slevomat/coding-standard
  - phpcs -i
  - vendor/bin/phpunit --no-coverage
